#
# Github Action to build container images to be available on Docker HUB.
#
#  * Repositories must be named as "image-[NAME]" or will be skipped;
#  * Dockerfile is expected on repository root;
#  * Push image to Docker HUB except when trigged by Pull Request;
#
#  This action should be used for public and privates images;
#  Please, set image as private on Docker HUB settings as need;
#

# Workflow name
name: Build Container Image to Docker HUB

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'

# Just one job at this time
jobs:

  # Job name
  Job-Docker-Build:

    # Github Action runner
    runs-on: ubuntu-latest

    # Job condition to run
    # Required because container image name is retrived from image-[NAME]
    if: startsWith(github.event.repository.name, 'image-')

    # Tasks
    steps:
      - name: Checkout repository as working directory
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set vars
        id: vars
        run: |
          # Abort Github action if repository not startswith image-
          echo ${{ github.event.repository.name }} | grep -qE '^image-'

          # Get image name from repository name
          DOCKER_REPO=$( echo ${{ github.event.repository.name }} | cut -f2- -d-)
          echo "::set-output name=repo::${DOCKER_REPO}"

          # Get TAG on format expected by Flux for get latest from correct sorting
          SHORT_SHA=$(git log --format="%H" -n 1 | cut -c1-7)
          TAG=$(date -u +${SHORT_SHA}-%Y%m%dT%H%M)
          echo "::set-output name=tag::${TAG}"
 
      - name: Docker build and push
        uses: docker/build-push-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          push: true
          tags: webera/${{ steps.vars.outputs.repo }}:latest,webera/${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.tag }}
